services:
  worker:
    build:
      context: . 
      dockerfile: docker/worker/Dockerfile
    container_name: worker
    ports:
      - "8080:8000"
  master:
    build:
      context: . 
      dockerfile: docker/master/Dockerfile
    container_name: master
    ports:
      - "8081:8000"
  upload:
    build:
      context: . 
      dockerfile: docker/upload/Dockerfile
    container_name: upload
    ports:
      - "8082:8000"