# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: master.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "master.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cmaster.proto\x12\tmapreduce\x1a\x1bgoogle/protobuf/empty.proto"C\n\x12RegisterServiceMes\x12\x17\n\x0fservice_address\x18\x01 \x01(\t\x12\x14\n\x0cservice_port\x18\x02 \x01(\x05\x32T\n\x06Master\x12J\n\x0fRegisterService\x12\x1d.mapreduce.RegisterServiceMes\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "master_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REGISTERSERVICEMES"]._serialized_start = 56
    _globals["_REGISTERSERVICEMES"]._serialized_end = 123
    _globals["_MASTER"]._serialized_start = 125
    _globals["_MASTER"]._serialized_end = 209
# @@protoc_insertion_point(module_scope)
