# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 1, "", "service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rservice.proto\x12\tmapreduce\x1a\x1bgoogle/protobuf/empty.proto"4\n\x07MapTask\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x16\n\x0enum_partitions\x18\x02 \x01(\x05"&\n\x0bMapResponse\x12\x17\n\x0fpartition_paths\x18\x01 \x03(\t"O\n\nReduceTask\x12\x13\n\x0bnum_mappers\x18\x01 \x01(\x05\x12\x17\n\x0fpartition_paths\x18\x02 \x03(\t\x12\x13\n\x0boutput_path\x18\x03 \x01(\t"%\n\x0eReduceResponse\x12\x13\n\x0boutput_path\x18\x01 \x01(\t"D\n\x13ReduceChangePathMes\x12\x11\n\tmapper_id\x18\x01 \x01(\x05\x12\x1a\n\x12new_partition_path\x18\x02 \x01(\t2\x8f\x02\n\tMapReduce\x12\x41\n\x0bWatchHealth\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty"\x00\x30\x01\x12\x33\n\x03Map\x12\x12.mapreduce.MapTask\x1a\x16.mapreduce.MapResponse"\x00\x12<\n\x06Reduce\x12\x15.mapreduce.ReduceTask\x1a\x19.mapreduce.ReduceResponse"\x00\x12L\n\x10ReduceChangePath\x12\x1e.mapreduce.ReduceChangePathMes\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_MAPTASK"]._serialized_start = 57
    _globals["_MAPTASK"]._serialized_end = 109
    _globals["_MAPRESPONSE"]._serialized_start = 111
    _globals["_MAPRESPONSE"]._serialized_end = 149
    _globals["_REDUCETASK"]._serialized_start = 151
    _globals["_REDUCETASK"]._serialized_end = 230
    _globals["_REDUCERESPONSE"]._serialized_start = 232
    _globals["_REDUCERESPONSE"]._serialized_end = 269
    _globals["_REDUCECHANGEPATHMES"]._serialized_start = 271
    _globals["_REDUCECHANGEPATHMES"]._serialized_end = 339
    _globals["_MAPREDUCE"]._serialized_start = 342
    _globals["_MAPREDUCE"]._serialized_end = 613
# @@protoc_insertion_point(module_scope)
