apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-app
  labels:
    app: master-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-app
  template:
    metadata:
      labels:
        app: master-app
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: [ "sh", "-c", "chown -R 10001:10001 /mapreduce" ]
        volumeMounts:
          - mountPath: /mapreduce
            name: fileserver
      containers:
      - name: master-container
        image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/irio-map-reduce-master:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /mapreduce
          name: fileserver
      volumes:
      - name: fileserver
        persistentVolumeClaim:
          claimName: fileserver