apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-app
  labels:
    app: master-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-app
  template:
    metadata:
      labels:
        app: master-app
    spec:
      containers:
      - name: master-container
        image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/irio-map-reduce-master:v$IMAGE_REMOTE_VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /mapreduce
          name: fileserver
        env:
        - name: SHARED_DIR
          value: /mapreduce
      volumes:
      - name: fileserver
        persistentVolumeClaim:
          claimName: fileserver
      

---

apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  selector:
    app: master-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  type: LoadBalancer
