apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    app: worker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-container
        image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME/irio-map-reduce-worker:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /mapreduce
          name: fileserver
      volumes:
      - name: fileserver
        persistentVolumeClaim:
          claimName: fileserver